# Generated by Django 4.1.5 on 2023-02-08 11:07

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category_images', models.ImageField(upload_to='category_images/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('product_description', models.TextField(max_length=512)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('quantity', models.DecimalField(blank=True, decimal_places=0, max_digits=3)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
