# Generated by Django 4.1.5 on 2023-02-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web_parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(blank=True, max_length=200, null=True)),
                ('web_description', models.CharField(blank=True, max_length=400, null=True)),
                ('web_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('web_number', models.CharField(blank=True, max_length=200, null=True)),
                ('web_email', models.EmailField(blank=True, default='info@astronaut.ge', max_length=254, null=True)),
                ('web_info_adress', models.CharField(blank=True, max_length=300, null=True)),
                ('web_info_adress_city', models.CharField(blank=True, max_length=300, null=True)),
                ('web_currency', models.CharField(choices=[('GEL', 'Georgian Lari'), ('USD', 'USD Dolar'), ('EUR', 'EURO')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Web_Seo_parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('web_seo_description', models.CharField(blank=True, max_length=400, null=True)),
                ('web_seo_author', models.CharField(blank=True, max_length=100, null=True)),
                ('web_seo_keywords', models.TextField(blank=True, max_length=800, null=True)),
                ('web_seo_robots', models.CharField(choices=[('Enable', 'Allow Robots'), ('Disable', 'DisAllow Robots')], max_length=100)),
                ('web_social_name', models.CharField(blank=True, max_length=200, null=True)),
                ('web_social_description', models.TextField(blank=True, max_length=800, null=True)),
                ('web_social_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
            ],
        ),
    ]
