# Generated by Django 4.1.5 on 2023-02-08 11:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('menu_description', ckeditor.fields.RichTextField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_image', models.ImageField(default='default.jpg', upload_to='menu_images/')),
            ],
        ),
    ]
